#include "reduce_base.hpp"
namespace uniconn {

UNC_SHMEM_REPT_FOR_BITWISE_REDUCE_TYPE_OP_MODE_HOST(DECL_FUNC_HOST, min, ReductionOperator::MIN)
UNC_SHMEM_REPT_FOR_BITWISE_REDUCE_TYPE_OP_MODE_GROUP_DEVICE(DECL_FUNC_DEVICE, min, ReductionOperator::MIN)
UNC_SHMEM_REPT_FOR_ARITH_REDUCE_TYPE_OP_MODE_HOST(DECL_FUNC_HOST, min, ReductionOperator::MIN)
UNC_SHMEM_REPT_FOR_ARITH_REDUCE_TYPE_OP_MODE_GROUP_DEVICE(DECL_FUNC_DEVICE, min, ReductionOperator::MIN)
}  // namespace uniconn